### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by boileaum** [pnavaro/python-notebooks#1]
Hello @pnavaro, any LICENSE file for this content?  
Thanks for publishing!

**Comment by pnavaro** [comment]
This one ? what do you think ?
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Licence Creative Commons Attribution - Pas d’Utilisation Commerciale 4.0 International</a>.

**Comment by boileaum** [comment]
Yes, it is the type of license I use for this kind of content.

**Comment by pnavaro** [comment]
Merci Matthieu.
