### ISSUE TITLE
map function

### ISSUE THREAD

**Issue by bclmary** [pnavaro/python-notebooks#2]
In chapter 4, it is stated that map function is more fast than for loop. An example is given comparing a comprehension list and map function. But map function returns an iterator, and the comprehension list example returns... a list. So these operations are not comparable. At least, you can compare:
`lmap = map(f,M)` with `lfor = (f(m) for m in M)`, which is a comprehension that returns an iterator. It turns out that map is actually faster than iterator comprehension, but less than twice.

**Comment by pnavaro** [comment]
You're absolutely right, thanks for your comment.
